openapi: 3.0.0
info:
  title: Medical Appointment Backend
  version: 1.0.0
  description: API de gestión de citas médicas

servers:
  - url: https://ndb65zvz61.execute-api.us-east-1.amazonaws.com/dev

paths:

  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK

  /appointments:
    post:
      summary: Crear cita médica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - insuredId
                - scheduleId
                - countryISO
              properties:
                insuredId:
                  type: string
                  example: "00001"
                scheduleId:
                  type: number
                  example: 100
                countryISO:
                  type: string
                  example: "PE"
      responses:
        "200":
          description: Cita creada

  /appointments/{insuredId}:
    get:
      summary: Obtener citas por insuredId
      parameters:
        - in: path
          name: insuredId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de citas