service: medical-appointment-backend

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

  environment:
    DYNAMODB_TABLE: AppointmentsTable
    SNS_TOPIC_ARN: !Ref AppointmentTopic
    SQS_PE_URL: !Ref SQSPE
    SQS_CL_URL: !Ref SQSCL
    SQS_CONFIRMATION_URL: !Ref SQSConfirmation

functions:

  health:
    handler: dist/presentation/handlers/health.handler
    events:
      - http:
          path: health
          method: get

  createAppointment:
    handler: dist/presentation/handlers/createAppointment.handler
    events:
      - http:
          path: appointments
          method: post

  getAppointments:
    handler: dist/presentation/handlers/getAppointments.handler
    events:
      - http:
          path: appointments/{insuredId}
          method: get

  appointmentPE:
    handler: dist/presentation/handlers/appointmentPE.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSPE, Arn]

  appointmentCL:
    handler: dist/presentation/handlers/appointmentCL.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSCL, Arn]

  appointmentStatusUpdater:
    handler: dist/presentation/handlers/appointmentStatusUpdater.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [SQSConfirmation, Arn]

  docs:
    handler: dist/presentation/handlers/docs.handler
    events:
      - http:
          path: docs
          method: get

resources:
  Resources:

    AppointmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AppointmentsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: insuredId
            AttributeType: S
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: insuredId
            KeyType: HASH
          - AttributeName: appointmentId
            KeyType: RANGE

    AppointmentTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: appointment-topic

    SQSPE:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_PE

    SQSCL:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CL

    SQSConfirmation:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: SQS_CONFIRMATION

plugins: []